parameters:
#    phpmagazin_rest.example.class: Phpmagazin\RestBundle\Example

services:
#    phpmagazin_rest.example:
#        class: %phpmagazin_rest.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
